export const INIT_PARAMS = 'SHOP::INIT_PARAMS';
export const ADD_TO_CART = 'SHOP::ADD_TO_CART';
export const PURCHASE_CART = 'SHOP::PURCHASE_CART';
export const UPDATE_PAGE_SIZE = 'SHOP::UPDATE_PAGE_SIZE';
export const UPDATE_PAGE_NUMBER = 'SHOP::UPDATE_PAGE_NUMBER';